-- NO "CREATE DATABASE" OR "USE" IN ORACLE
-- CONNECT AS YOUR USER/SCHEMA DIRECTLY

-- CREATE DEPARTMENT TABLE
CREATE TABLE department (
    DNAME       VARCHAR2(50),
    DNUMBER     NUMBER PRIMARY KEY,
    MGRSSN      VARCHAR2(15),
    MGRSTARTDATE DATE
);

-- CREATE EMPLOYEE TABLE
CREATE TABLE employee (
    FNAME     VARCHAR2(255),
    MINIT     CHAR(1),
    LNAME     VARCHAR2(20),
    SSN       VARCHAR2(15) PRIMARY KEY,
    BDATE     DATE,
    ADDRESS   VARCHAR2(30),
    SEX       CHAR(1),
    SALARY    NUMBER,
    SUPERSSON VARCHAR2(15),
    DNO       NUMBER,
    CONSTRAINT fk_dno FOREIGN KEY (DNO)
    REFERENCES department(DNUMBER)
);

-- INSERT INTO DEPARTMENT
INSERT INTO department VALUES ('Research', 1, 'asfds', TO_DATE('2000-01-01', 'YYYY-MM-DD'));
INSERT INTO department VALUES ('Sales',    2, 'asdas', TO_DATE('2005-03-15', 'YYYY-MM-DD'));
INSERT INTO department VALUES ('HR',       3, 'asdasd', TO_DATE('2010-06-20', 'YYYY-MM-DD'));

-- INSERT INTO EMPLOYEE
INSERT INTO employee (FNAME, MINIT, LNAME, SSN, BDATE, ADDRESS, SEX, SALARY, SUPERSSON, DNO)
VALUES ('John',    'A', 'Smith',    '1001', TO_DATE('1990-05-12', 'YYYY-MM-DD'), 'Kathmandu',  'M', 50000, NULL,   1);

INSERT INTO employee (FNAME, MINIT, LNAME, SSN, BDATE, ADDRESS, SEX, SALARY, SUPERSSON, DNO)
VALUES ('Sara',    'B', 'Johnson',  '1002', TO_DATE('1992-08-21', 'YYYY-MM-DD'), 'Lalitpur',   'F', 60000, '1001', 2);

INSERT INTO employee (FNAME, MINIT, LNAME, SSN, BDATE, ADDRESS, SEX, SALARY, SUPERSSON, DNO)
VALUES ('Michael', 'C', 'Brown',    '1003', TO_DATE('1988-03-15', 'YYYY-MM-DD'), 'Bhaktapur',  'M', 55000, '1001', 1);

INSERT INTO employee (FNAME, MINIT, LNAME, SSN, BDATE, ADDRESS, SEX, SALARY, SUPERSSON, DNO)
VALUES ('Emily',   'D', 'Davis',    '1004', TO_DATE('1995-11-30', 'YYYY-MM-DD'), 'Pokhara',    'F', 48000, '1002', 3);

INSERT INTO employee (FNAME, MINIT, LNAME, SSN, BDATE, ADDRESS, SEX, SALARY, SUPERSSON, DNO)
VALUES ('David',   'E', 'Wilson',   '1005', TO_DATE('1987-07-19', 'YYYY-MM-DD'), 'Biratnagar', 'M', 70000, NULL,   2);

INSERT INTO employee (FNAME, MINIT, LNAME, SSN, BDATE, ADDRESS, SEX, SALARY, SUPERSSON, DNO)
VALUES ('Sophia',  'F', 'Taylor',   '1006', TO_DATE('1993-01-25', 'YYYY-MM-DD'), 'Butwal',     'F', 52000, '1005', 3);

INSERT INTO employee (FNAME, MINIT, LNAME, SSN, BDATE, ADDRESS, SEX, SALARY, SUPERSSON, DNO)
VALUES ('Daniel',  'G', 'Anderson', '1007', TO_DATE('1991-09-10', 'YYYY-MM-DD'), 'Chitwan',    'M', 58000, '1003', 1);

-- COMMIT TO SAVE ALL INSERTS
COMMIT;

-- SELECT ALL
SELECT * FROM department;
SELECT * FROM employee;

-- 10% SALARY RAISE FOR RESEARCH DEPARTMENT
SELECT E.FNAME, E.LNAME,
       E.SALARY * 1.1 AS INCREASED_SALARY
FROM employee E
JOIN department D ON E.DNO = D.DNUMBER
WHERE D.DNAME = 'Research';

-- SALARY STATISTICS FOR HR DEPARTMENT
SELECT
    SUM(E.SALARY) AS TOTAL,
    MAX(E.SALARY) AS MAX,
    MIN(E.SALARY) AS MIN,
    AVG(E.SALARY) AS AVERAGE
FROM employee E
JOIN department D ON E.DNO = D.DNUMBER
WHERE D.DNAME = 'HR';

-- EMPLOYEES CONTROLLED BY DEPARTMENT NO 5
SELECT FNAME, LNAME FROM employee E
WHERE EXISTS (
    SELECT * FROM employee
    WHERE DNO = 5
);

-- DEPARTMENTS HAVING AT LEAST 2 EMPLOYEES
SELECT D.DNAME, COUNT(*) AS EMP_COUNT
FROM employee E
JOIN department D ON E.DNO = D.DNUMBER
GROUP BY D.DNUMBER, D.DNAME
HAVING COUNT(*) >= 2;

-- EMPLOYEES BORN IN THE 1990s
SELECT *
FROM employee
WHERE EXTRACT(YEAR FROM BDATE) BETWEEN 1990 AND 1999;